// <auto-generated />
using System;
using HockeyProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HockeyProject.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20201111220446_HockeyProj")]
    partial class HockeyProj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HockeyProject.Models.Coach", b =>
                {
                    b.Property<int>("CoachID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CareerWins")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasKey("CoachID");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            CoachID = 1,
                            CareerWins = 689,
                            CoachName = "Alain Vigneault",
                            Country = "Canada",
                            DateOfBirth = new DateTime(1961, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CoachID = 2,
                            CareerWins = 284,
                            CoachName = "Mike Sullivan",
                            Country = "US",
                            DateOfBirth = new DateTime(1968, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HockeyProject.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Assists")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Goals")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerID = 1,
                            Assists = 32,
                            Country = "Canada",
                            DateOfBirth = new DateTime(1988, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Goals = 21,
                            PlayerName = "Claude Giroux",
                            Position = "Center"
                        },
                        new
                        {
                            PlayerID = 2,
                            Assists = 31,
                            Country = "Canada",
                            DateOfBirth = new DateTime(1987, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Goals = 16,
                            PlayerName = "Sidney Crosby",
                            Position = "Center"
                        });
                });

            modelBuilder.Entity("HockeyProject.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Losses")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wins")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("TeamID");

                    b.HasIndex("CoachID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            CoachID = 1,
                            Conference = "Eastern",
                            Losses = 21,
                            PlayerID = 1,
                            TeamName = "Philadelphia Flyers",
                            Wins = 41
                        },
                        new
                        {
                            TeamID = 2,
                            CoachID = 2,
                            Conference = "Eastern",
                            Losses = 23,
                            PlayerID = 2,
                            TeamName = "Pittsburgh Penguins",
                            Wins = 40
                        });
                });

            modelBuilder.Entity("HockeyProject.Models.Team", b =>
                {
                    b.HasOne("HockeyProject.Models.Coach", "CoachName")
                        .WithMany()
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HockeyProject.Models.Player", "PlayerName")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
